# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!
  BIN: ./bin
  SRC: '*.go'
  CLI: pd

includes:
  build: ./Taskfile_{{OS}}.yml

tasks:
  fmt:
    cmds:
      - gofmt -l {{ .SRC }} || (gofmt -d $(SRC); exit 1)

  lint:
    cmds:
      - golangci-lint run -v

  test: 
    deps: 
      - install_deps 
      - lint
    cmds:
      - richgo test -v ./...

  cli: 
    cmds:
      - task build:cli 

  install_deps:
    cmds:
      - go get -v ./...

  winc:
    env:
      GOOS: windows
      GOARCH: 386
      # CGO_ENABLED: 1
      # CXX: i686-w64-mingw32-g++
      # CC: i686-w64-mingw32-gcc
    cmds:
      - mkdir -p {{ .BIN }}
      - go build -o {{ .BIN }}/{{ .CLI }}.exe

  linuxc:
    env:
      GOOS: linux
      GOARCH: 386
      # CGO_ENABLED: 1
      # CXX: i686-w64-mingw32-g++
      # CC: i686-w64-mingw32-gcc
    cmds:
      - mkdir -p {{ .BIN }}
      - go build -o {{ .BIN }}/{{ .CLI }}_


  clean:
    cmds:
      - rm -rf {{ .BIN }}
  default:
    deps:
      - cli
    cmds:
      - task -l
      # - echo "{{.GREETING}}"

    silent: true
